apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-hbs-web
  labels:
    app: blog-hbs-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-hbs-web
  template:
    metadata:
      labels:
        app: blog-hbs-web
    spec:
      containers:
        - name: blog-hbs-web
          image: blog-hbs-web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: blog-hbs-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: blog-hbs-web
